version: '3'
services:
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home

volumes:
  jenkins-log:
  jenkins-data:

